// Generated by `pnpm --filter @gekichumai/admin-contract openapi:compatibility:update`.
// Do not edit this value by hand.
export const ADMIN_CONTRACT_COMPATIBILITY_ID =
  'sha256:83459aaaed880eac2c5c52a488c6fb67eace6d2217cf454479adacd4f9f5c3a7' as const