// Generated by `pnpm --filter @gekichumai/admin-contract openapi:compatibility:update`.
// Do not edit this value by hand.
export const ADMIN_CONTRACT_COMPATIBILITY_ID =
  'sha256:d23d522b049a6b9bd74a19f186bf070e838e5f204fc157cfeef54f3f6d6c2e5f' as const