// Generated by `pnpm --filter @gekichumai/admin-contract openapi:compatibility:update`.
// Do not edit this value by hand.
export const ADMIN_CONTRACT_COMPATIBILITY_ID =
  'sha256:5f5261616e1faa37d6360a69005e97d33ba8befe5848bc6979ba214d6f849bd3' as const