packages:
  - apps/*
  - packages/*
  - scripts/*

catalog:
  '@better-auth/passkey': ^1.5.6
  '@orpc/client': ^1.14.0
  '@orpc/contract': ^1.14.0
  '@orpc/openapi': ^1.14.0
  '@orpc/openapi-client': ^1.14.0
  '@orpc/react': ^1.14.0
  '@orpc/server': ^1.14.0
  '@orpc/tanstack-query': ^1.14.0
  '@orpc/zod': ^1.14.0
  '@types/node': ^22.19.17
  '@types/pg': ^8.20.0
  '@types/react': ^19.2.8
  better-auth: ^1.5.6
  clsx: ^2.1.1
  dotenv: ^16.6.1
  esno: ^4.8.0
  fuse.js: ^7.3.0
  hono: ^4.12.14
  pg: ^8.20.0
  react: ^19.2.3
  ts-pattern: ^5.9.0
  typescript: ^5.9.3
  vitest: ^3.2.1
