export const demo = [
  {
    sheetId: '系ぎて__dxrt__dx__dxrt__expert',
    achievementRate: 100.2,
    achievementAccuracy: 'fc',
    achievementSync: 'sp',
    playCount: 5,

    achievementDXScore: {
      achieved: 970,
      total: 1000,
    },
  },
  {
    sheetId: 'Λzure Vixen__dxrt__dx__dxrt__expert',
    achievementRate: 100.5,
    achievementAccuracy: 'fcp',
    achievementSync: 'fsp',
    playCount: 2,
    achievementDXScore: {
      achieved: 970,
      total: 1000,
    },
  },
  {
    sheetId: 'INTERNET OVERDOSE__dxrt__dx__dxrt__master',
    achievementRate: 100.6,
    achievementAccuracy: 'ap',
    achievementSync: 'fsd',
    playCount: 3,
    achievementDXScore: {
      achieved: 2123,
      total: 2323,
    },
  },
  {
    sheetId: '偉大なる悪魔は実は大天使パトラちゃん様なのだ！__dxrt__dx__dxrt__master',
    achievementRate: 100.0,
    achievementAccuracy: 'app',
    achievementSync: 'fsdp',
    playCount: 4,
    achievementDXScore: {
      achieved: 1234,
      total: 1234,
    },
  },
  { sheetId: 'エゴロック__dxrt__dx__dxrt__master', achievementRate: 100.2, playCount: 1 },
  { sheetId: '終点__dxrt__std__dxrt__master', achievementRate: 100.4, playCount: 1 },
  { sheetId: 'ラグトレイン__dxrt__dx__dxrt__master', achievementRate: 100.6, playCount: 1 },
  { sheetId: 'ロータスイーター__dxrt__dx__dxrt__master', achievementRate: 100.7, playCount: 1 },
  {
    sheetId: 'ウミユリ海底譚__dxrt__std__dxrt__master',
    achievementRate: 100.5,
    playCount: 1,
    achievementDXScore: {
      achieved: 950,
      total: 1000,
    },
  },
  { sheetId: '吉原ラメント__dxrt__std__dxrt__master', achievementRate: 100.0 },
  {
    sheetId: 'スカーレット警察のゲットーパトロール24時__dxrt__dx__dxrt__master',
    achievementRate: 100.5,
  },
  {
    sheetId: '不思議の国のクリスマス__dxrt__std__dxrt__master',
    achievementRate: 100.6,
    achievementDXScore: {
      achieved: 930,
      total: 1000,
    },
  },
  {
    sheetId: 'OMAKENO Stroke__dxrt__dx__dxrt__master',
    achievementRate: 100.4,
    achievementDXScore: {
      achieved: 910,
      total: 1000,
    },
  },
  { sheetId: 'Final Step!__dxrt__dx__dxrt__master', achievementRate: 100.1 },
  { sheetId: 'Cthugha__dxrt__dx__dxrt__master', achievementRate: 100.3 },
  {
    sheetId: 'Make Up Your World feat. キョンシーのCiちゃん & らっぷびと__dxrt__dx__dxrt__master',
    achievementRate: 100.5,
  },
  {
    sheetId: 'Knight Rider__dxrt__dx__dxrt__master',
    achievementRate: 100.1,
    achievementDXScore: {
      achieved: 900,
      total: 1000,
    },
    playCount: 21,
    newRecordCount: 19,
  },
  { sheetId: 'コンティニュー！ feat. 藍月なくる__dxrt__dx__dxrt__master', achievementRate: 100.5 },
  {
    sheetId: 'Complex Mind__dxrt__dx__dxrt__master',
    achievementRate: 100.3,
    achievementDXScore: {
      achieved: 890,
      total: 1000,
    },
    playCount: 19,
    newRecordCount: 4,
  },
  { sheetId: 'Luminaria__dxrt__dx__dxrt__master', achievementRate: 100.1 },
  { sheetId: 'NULCTRL__dxrt__dx__dxrt__master', achievementRate: 100.0 },
  { sheetId: 'シックスプラン__dxrt__dx__dxrt__master', achievementRate: 100.6 },
  { sheetId: 'Geranium__dxrt__dx__dxrt__master', achievementRate: 100.5 },
  { sheetId: 'Falling__dxrt__dx__dxrt__master', achievementRate: 100.5 },
  { sheetId: 'とびだせ！TO THE COSMIC!!__dxrt__dx__dxrt__master', achievementRate: 100.6 },
  {
    sheetId: 'Cider P@rty__dxrt__dx__dxrt__master',
    achievementRate: 100.5,
    achievementDXScore: {
      achieved: 850,
      total: 1000,
    },
    playCount: 1,
    newRecordCount: 1,
  },
  { sheetId: 'You Mean the World to Me__dxrt__dx__dxrt__master', achievementRate: 100.4 },
  { sheetId: 'Transcend Lights__dxrt__dx__dxrt__master', achievementRate: 100.5 },
  {
    sheetId: 'Last Kingdom__dxrt__dx__dxrt__master',
    achievementRate: 100.5,
    playCount: 21,
    newRecordCount: 19,
  },
  { sheetId: "Don't Fight The Music__dxrt__dx__dxrt__master", achievementRate: 99.9 },
  {
    sheetId: 'INTERNET YAMERO__dxrt__dx__dxrt__remaster',
    achievementRate: 100.3,
    achievementDXScore: {
      achieved: 820,
      total: 1000,
    },
  },
  { sheetId: '青春コンプレックス__dxrt__dx__dxrt__remaster', achievementRate: 100.2 },
  { sheetId: 'バグ__dxrt__dx__dxrt__remaster', achievementRate: 100.1 },
  { sheetId: '神っぽいな__dxrt__dx__dxrt__remaster', achievementRate: 100.6 },
  { sheetId: 'ラビットホール__dxrt__dx__dxrt__remaster', achievementRate: 100.7 },
  { sheetId: '愛包ダンスホール__dxrt__dx__dxrt__master', achievementRate: 100.4 },
  { sheetId: 'マツケンサンバⅡ__dxrt__dx__dxrt__master', achievementRate: 100.5 },
  { sheetId: 'デビルじゃないもん__dxrt__dx__dxrt__master', achievementRate: 100.7 },
  { sheetId: 'リアライズ__dxrt__dx__dxrt__master', achievementRate: 100.4 },
  { sheetId: '人マニア__dxrt__dx__dxrt__master', achievementRate: 99.7 },
  {
    sheetId: 'イガク__dxrt__dx__dxrt__master',
    achievementRate: 99.3,
    achievementDXScore: {
      achieved: 0,
      total: 1000,
    },
  },
  { sheetId: '病み垢ステロイド__dxrt__dx__dxrt__master', achievementRate: 100.1 },
  { sheetId: 'Ultimate taste__dxrt__dx__dxrt__master', achievementRate: 100.5 },
  { sheetId: 'Chronomia__dxrt__dx__dxrt__master', achievementRate: 97.9 },
  { sheetId: 'パラドクスイヴ__dxrt__dx__dxrt__master', achievementRate: 99.1 },
  { sheetId: 'YKWTD__dxrt__dx__dxrt__master', achievementRate: 99.4 },
  { sheetId: 'プリズム△▽リズム__dxrt__dx__dxrt__master', achievementRate: 100.5 },
  { sheetId: '勇者__dxrt__dx__dxrt__remaster', achievementRate: 100.0 },
  { sheetId: '唱__dxrt__dx__dxrt__remaster', achievementRate: 99.6 },
  { sheetId: 'ダーリンダンス__dxrt__dx__dxrt__remaster', achievementRate: 100.2 },
]
