import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { computeAdminContractCompatibilityId } from '../src/openapi.js'

const destination = fileURLToPath(new URL('../src/compatibility.ts', import.meta.url))
const compatibilityId = await computeAdminContractCompatibilityId()
const source = `// Generated by \`pnpm --filter @gekichumai/admin-contract openapi:compatibility:update\`.\n// Do not edit this value by hand.\nexport const ADMIN_CONTRACT_COMPATIBILITY_ID =\n  '${compatibilityId}' as const\n`

await writeFile(destination, source, 'utf8')
console.log(`Updated administrator contract compatibility identifier to ${compatibilityId}.`)