name: Sync Supabase

on:
  push:
    # trigger on supabase path push
    branches:
      - main
    paths:
      - 'supabase/**'

concurrency:
  group: supabase-${{ github.ref }}

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    name: Deploy Supabase Edge Functions

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy --project-ref $PROJECT_ID
